version: '3'

services:
    proxy:
        image: reverseproxy
        ports:
            - 80:80
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

    flask:
        build: ./python_images/.
        restart: always
        expose: 
            - "5000"
    redis:
        image: "redis:alpine"

    static:
        image: nginx:latest
        volumes:
            - ./nginx_static/templates:/usr/share/nginx/html:ro
        restart: always
        expose: 
            - "80"